function main()
    player.MoveTo("up", 3)
    coroutine.yield()
    message.ShowMessage("勇者「うぎゃーー！！！")
    coroutine.yield()
    message.ShowMessage("姫「ちょっと大きな声を出して\n　　　どうしたの？")
    npcGirl.MoveTo("right", 6)
    coroutine.yield()
    message.ShowMessage("王「なんだ？なんだ？")
    npcBoy.Show(true)
    coroutine.yield()
    npcBoy.MoveTo("down", 4)
    coroutine.yield()
    npcBoy.MoveTo("left", 2)
    coroutine.yield()
    message.ShowMessage("勇者「ない！ないんだ！")
    coroutine.yield()
    message.ShowMessage("勇者「ないんだよ！！！\n　　　俺のチョコが！！！")
    coroutine.yield()
    message.ShowMessage("姫「またぁー\nそもそももらってないんじゃないの？")
    coroutine.yield()
    message.ShowMessage("勇者「んなことないよ！\nバイト前にもらってここに置いて行ってからバイトにいったんだから")
    coroutine.yield()
    message.ShowMessage("勇者「まさか！お前が食べたんじゃないだろな？")
    coroutine.yield()
    message.ShowMessage("姫「そそそ,,,そんなわけないでしょ！\nチョコなんか友達からいっぱいもらってるし")
    coroutine.yield()
    message.ShowMessage("姫「証拠もないのに疑うのはやめてよね")
    coroutine.yield()
    message.ShowMessage("勇者「くやしい,,,くらしすぎるよ,,,\nもう寝る！！！ほっといてよ！！！")
    coroutine.yield()
    player.MoveTo("right", 2)
    npcBoy.MoveTo("right", 2)
    coroutine.yield()
    player.MoveTo("up", 2)
    coroutine.yield()
    player.MoveTo("right", 4)
    coroutine.yield()
    player.MoveTo("up", 4)
    coroutine.yield()
    message.ShowMessage("姫「なんだか,かわいそうね,,,")
    coroutine.yield()
    message.ShowMessage("王「そ,,,そだね,,,")
    coroutine.yield()
    camera.JumpTo("up", 10)
    coroutine.yield()
    message.ShowMessage("勇者「くそぉーーー")
    coroutine.yield()
    message.ShowMessage("勇者「うえぇぇーーん")
    player.MoveTo("up", 3)
    coroutine.yield()
    player.MoveTo("left", 10)
    coroutine.yield()
    npcBoy.NormalSpeedPoint()
end