function main()
    fadePanel.PlayFadeIn()
    coroutine.yield()
    player.MoveTo("up", 3)
    coroutine.yield()
    message.ShowMessage("勇者「やったー！やったー！\nXXちゃんからチョコをもらった！")
    coroutine.yield()
    message.ShowMessage("勇者「僕はリア充だ！やったー！")
    coroutine.yield()
    message.ShowMessage("勇者「やべ！こんな時間だ！スライム討伐のバイトがあったんだ！\nチョコは後で食べよう！")
    coroutine.yield()
    message.ShowMessage("勇者「いそげ！いそげーーー！")
    coroutine.yield()
    player.MoveTo("down", 3)
    coroutine.yield()
    fadePanel.PlayFadeOut()
    coroutine.yield()
    message.ClearMessage()
    coroutine.yield()
    message.Wait(1)
    coroutine.yield()
    message.ShowMessage("1時間後...")
    coroutine.yield()
    message.Wait(1)
    coroutine.yield()
    fadePanel.PlayFadeIn()
    coroutine.yield()
    message.ShowMessage("勇者「あー今日もスライム討伐がんばったぞー！！")
    coroutine.yield()
    player.MoveTo("up", 3)
    coroutine.yield()
    message.ShowMessage("勇者「うぎゃーー！！！")
    coroutine.yield()
    message.ShowMessage("姫「ちょっと大きな声を出して\n　　　どうしたの？")
    npcGirl.MoveTo("right", 6)
    coroutine.yield()
    message.ShowMessage("王「なんだ？なんだ？")
    npcBoy.Show(true)
    coroutine.yield()
    npcBoy.MoveTo("down", 4)
    coroutine.yield()
    npcBoy.MoveTo("left", 2)
    coroutine.yield()
    message.ShowMessage("勇者「ない！ないんだ！")
    coroutine.yield()
    message.ShowMessage("勇者「ないんだよ！！！\n　　　俺のチョコが！！！")
    coroutine.yield()
    message.ShowMessage("姫「またぁー\nそもそももらってないんじゃないの？")
    coroutine.yield()
    message.ShowMessage("勇者「んなことないよ！\nバイト前にもらってここに置いて行ってからバイトにいったんだから")
    coroutine.yield()
    message.ShowMessage("勇者「まさか！お前が食べたんじゃないだろな？")
    coroutine.yield()
    message.ShowMessage("姫「そそそ,,,そんなわけないでしょ！\nチョコなんか友達からいっぱいもらってるし")
    coroutine.yield()
    message.ShowMessage("姫「証拠もないのに疑うのはやめてよね")
    coroutine.yield()
    message.ShowMessage("勇者「くやしい,,,くらしすぎるよ,,,\nもう寝る！！！ほっといてよ！！！")
    coroutine.yield()
    player.MoveTo("right", 2)
    npcBoy.MoveTo("right", 2)
    coroutine.yield()
    player.MoveTo("up", 2)
    coroutine.yield()
    player.MoveTo("right", 4)
    coroutine.yield()
    player.MoveTo("up", 4)
    coroutine.yield()
    message.ShowMessage("姫「なんだか,かわいそうね,,,")
    coroutine.yield()
    message.ShowMessage("王「そ,,,そだね,,,")
    coroutine.yield()
    camera.JumpTo("up", 10)
    coroutine.yield()
    message.ShowMessage("勇者「くそぉーーー")
    coroutine.yield()
    message.ShowMessage("勇者「うえぇぇーーん")
    player.MoveTo("up", 3)
    coroutine.yield()
    player.MoveTo("left", 10)
    coroutine.yield()
    message.ShowMessage("勇者「寝てやる！寝てやるぞ！！\nグッスン...")
    coroutine.yield()
    message.ShowMessage("勇者「(この布団甘い香りがするし少しあたたかいな...\n眠くなってきた...)")
    coroutine.yield()
    message.ShowMessage("勇者「...zzzZZZ")
    coroutine.yield()
    message.Wait(1)
    coroutine.yield()
    fadePanel.PlayFadeOut()
    coroutine.yield()

    message.Wait(0.5)
    coroutine.yield()
    message.ShowMessage("???「勇者よ...勇者よ...")
    coroutine.yield()
    message.ShowMessage("勇者「うん?なんだ?")
    coroutine.yield()
    message.ShowMessage("???「勇者よ...勇者よ..., \nそなたに特別な時計を授けよう.")
    coroutine.yield()
    message.ShowMessage("???「この時計は時空を超えることができる時計です.")
    coroutine.yield()
    message.ShowMessage("???「これを使って,魔王討伐に役立ててください.")
    coroutine.yield()
    message.ShowMessage("勇者「なんだ？なんだってんだよ,,,")
    coroutine.yield()
    message.ShowMessage("???「ただし,使えるのはたった1回のみ.\n戻った過去に滞在できるのは1時間です.")
    coroutine.yield()
    message.ShowMessage("???「有効に使うのですよ.魔王討伐は任せました.")
    coroutine.yield()
    message.Wait(0.5)
    coroutine.yield()
    message.ClearMessage()
    coroutine.yield()
    fadePanel.PlayFadeIn()
    coroutine.yield()
    message.Wait(1)
    coroutine.yield()
    message.ShowMessage("勇者「...は！！夢か！！")
    coroutine.yield()
    message.ShowMessage("チャリン...")
    coroutine.yield()
    message.ShowMessage("勇者「なんだこれ?とけい?なのか?")
    coroutine.yield()
    message.ShowMessage("勇者「確か...魔王討伐にどうのこうの...")
    coroutine.yield()
    message.ShowMessage("勇者「あと,過去に戻れるっていってたな...")
    coroutine.yield()
    message.ShowMessage("勇者「過去...過去!???")
    coroutine.yield()
    message.ShowMessage("勇者「それじゃこれでチョコを盗んだ犯人が\nわかるかもしれない!")
    coroutine.yield()
    message.ShowMessage("勇者「よーし!こうなったら絶対犯人を見つけてやるぞ！")
    coroutine.yield()
    message.ShowMessage("勇者「使い方は...自分の戻りたい日時にタイマーをセットして...")
    coroutine.yield()
    message.ShowMessage("勇者「まてよ...戻れるのは1回だけで\n滞在時間は１時間だから")
    coroutine.yield()
    message.ShowMessage("勇者「ちょうど僕がバイトにいく時間にセットすればいいか")
    coroutine.yield()
    message.ShowMessage("カチカチ")
    coroutine.yield()
    message.ShowMessage("勇者「よーし！これでスタートだ！！")
    coroutine.yield()
    message.ShowMessage("...")
    coroutine.yield()
    message.ShowMessage("...")
    coroutine.yield()
    message.ShowMessage("勇者「あれ?なにもおきない?")
    coroutine.yield()
    message.ShowMessage("...")
    coroutine.yield()
    message.ShowMessage("勇者「なんだよ...ウソかよ...\n ウソつきかよ!!")
    coroutine.yield()
    message.ShowMessage("カチ...")
    coroutine.yield()
    message.ShowMessage("カチ...カチ...カチ...\nカチ!カチ!カチ!カチ!")
    coroutine.yield()
    message.ShowMessage("勇者「うわぁーーーなんだーーー！！？\nうわーー！！うわーー！！")
    coroutine.yield()
    fadePanel.PlayFadeOut()
    coroutine.yield()
    message.Wait(0.5)
    coroutine.yield()
    message.ClearMessage()
    coroutine.yield()
    fadePanel.PlayFadeIn()
    coroutine.yield()
    message.Wait(1)
    coroutine.yield()
    message.ShowMessage("勇者「...は！夢だったのか!?")
    coroutine.yield()
    message.ShowMessage("勇者「えっと...時間は...\n俺がちょうどバイトにいく時間じゃないか！")
    coroutine.yield()
    message.ShowMessage("勇者「ほんとに過去にもどれたんだ!!!!")
    coroutine.yield()
    message.ShowMessage("勇者「こうしてられない!\n早速チョコを見張って犯人を見つけないと!")
    coroutine.yield()
    message.ShowMessage("勇者「絶対,姫か王だよ!!")
    coroutine.yield()
    player.MoveTo("right", 10)
    coroutine.yield()
    player.MoveTo("down", 4)
    coroutine.yield()
    oldPlayer.Show(true)
    npcGirl.JumpToPosition(-7,0)
    npcBoy.JumpToPosition(0,-4)
    npcBoy.Show(true)
    message.Wait(0.5)
    coroutine.yield()
    camera.JumpTo("down", 10)
    coroutine.yield()
    message.ShowMessage("勇者「(おっと...僕がまだいる...)")
    coroutine.yield()
    message.ShowMessage("過去勇者「やったー！やったー！\nXXちゃんからチョコをもらった！")
    coroutine.yield()
    message.ShowMessage("過去勇者「僕はリア充だ！やったー！")
    coroutine.yield()
    message.ShowMessage("過去勇者「やべ！こんな時間だ！スライム討伐のバイトがあったんだ！\nチョコは後で食べよう！")
    coroutine.yield()
    message.ShowMessage("過去勇者「いそげ！いそげーーー！")
    coroutine.yield()
    oldPlayer.MoveTo("down", 4)
    coroutine.yield()
    message.ShowMessage("勇者「(はた方みてると あの独り言って\n すごく痛いやつだな)")
    coroutine.yield()
    message.ShowMessage("勇者「なこと考えてる場合じゃなかった.\nこのまま隠れて見張っておこう.")
    coroutine.yield()
    message.Wait(0.5)
    coroutine.yield()

    message.ShowMessage("カッチ...カッチ...カッチ...")
    coroutine.yield()
    message.ShowMessage("カッチ...カッチ...カッチ...")
    coroutine.yield()
    message.ShowMessage("勇者「15分たっても誰もこないなぁ...")
    coroutine.yield()
    message.ShowMessage("???「あーあ...今日も疲れたー")
    coroutine.yield()
    message.ShowMessage("勇者「(お！..誰かくるぞ...)")
    coroutine.yield()
    npcGirl.MoveTo("right",7)
    message.ShowMessage("姫「もーほんとにやんなちゃうよー\n在宅なのにスライム倒せって")
    coroutine.yield()
    message.ShowMessage("姫「パワハラもいいとこじゃない")
    coroutine.yield()
    message.ShowMessage("姫「あ！何これチョコレートあんじゃん.\nラッキーあけちゃお！")
    coroutine.yield()
    message.ShowMessage("(パカッ)")
    coroutine.yield()
    message.ShowMessage("勇者「(姫！！やっぱあいつだったのか！！\nこうなったら懲らしめてやる！)")
    coroutine.yield()
    message.ShowMessage("姫「うん?でもこれ...手作りだね...\n私そうゆうの苦手だからなぁ...")
    coroutine.yield()
    message.ShowMessage("姫「執事に頼んで職人が作ったやつをもらおーっと")
    coroutine.yield()
    message.ShowMessage("姫「執事 執事ー")
    coroutine.yield()
    npcGirl.MoveTo("left",7)
    coroutine.yield()
    message.Wait(1)
    player.MoveTo("down",4)
    coroutine.yield()
    player.MoveTo("left",4)
    coroutine.yield()
    player.MoveTo("down",1)
    coroutine.yield()
    player.MoveTo("left",2)
    coroutine.yield()
    message.ShowMessage("勇者「たしかに ある. あれー姫じゃなかったのか.")
    coroutine.yield()

    message.ShowMessage("勇者「じゃあ いったい誰なんだろう...やべ誰か来る!")
    coroutine.yield()
    player.MoveTo("right",2)
    coroutine.yield()
    player.MoveTo("up",1)
    coroutine.yield()
    player.MoveTo("right",4)
    coroutine.yield()
    player.MoveTo("up",4)
    coroutine.yield()
    message.Wait(0.5)
    coroutine.yield()
    npcBoy.JumpToPosition(0,-4)
    npcBoy.Show(true)
    coroutine.yield()
    message.ShowMessage("王「あーあー今日も疲れたなぁ\n書類にハンコばっかり")
    coroutine.yield()
    npcBoy.MoveTo("up",4)
    message.ShowMessage("王「スライムの討伐指示出しても誰もやらないし\n困った家臣ばっかりだ.")
    coroutine.yield()
    message.ShowMessage("王「お！チョコあるじゃん.")
    coroutine.yield()
    message.ShowMessage("(パカッ)")
    coroutine.yield()
    message.ShowMessage("勇者「(王！！まさかあなたなのか！！\nあなたなんですね！！)")
    coroutine.yield()
    message.ShowMessage("王「うーむ.でも盗みはよくないね.\nつぼの中身を盗む勇者じゃあるまいし.")
    coroutine.yield()
    message.ShowMessage("王「早く布団で寝よーっと")
    coroutine.yield()
    npcBoy.MoveTo("right",3)
    coroutine.yield()
    npcBoy.MoveTo("up",5)
    coroutine.yield()
    npcBoy.Show(false)
    coroutine.yield()
    message.Wait(1)
    player.MoveTo("down",4)
    coroutine.yield()
    player.MoveTo("left",4)
    coroutine.yield()
    player.MoveTo("down",1)
    coroutine.yield()
    player.MoveTo("left",2)
    coroutine.yield()
    message.ShowMessage("勇者「なんか色々引っかかるけど.\n確かにある...")
    coroutine.yield()
    message.ShowMessage("勇者「2人じゃないとすると いったい\nだれなんだろうか...")
    coroutine.yield()
    message.ShowMessage("勇者「とりあえず しばらくみはっておこう.")
    coroutine.yield()
    player.MoveTo("right",2)
    coroutine.yield()
    player.MoveTo("up",1)
    coroutine.yield()
    player.MoveTo("right",4)
    coroutine.yield()
    player.MoveTo("up",4)
    coroutine.yield()
    message.Wait(0.5)
    coroutine.yield()

    message.ShowMessage("カッチ...カッチ...カッチ...")
    coroutine.yield()
    message.ShowMessage("カッチ...カッチ...カッチ...")
    coroutine.yield()
    fadePanel.PlayFadeOut()
    coroutine.yield()
    message.Wait(0.5)
    coroutine.yield()
    message.ShowMessage("カッチ...カッチ...カッチ...")
    coroutine.yield()
    message.ShowMessage("のこり滞在可能時間:5分")
    coroutine.yield()
    fadePanel.PlayFadeIn()
    coroutine.yield()
    message.Wait(0.5)
    message.ShowMessage("勇者「あーもう時間がない!")
    coroutine.yield()
    player.MoveTo("down",4)
    coroutine.yield()
    player.MoveTo("left",4)
    coroutine.yield()
    player.MoveTo("down",1)
    coroutine.yield()
    player.MoveTo("left",2)
    coroutine.yield()
    message.ShowMessage("勇者「この世界にいられるのはあと数分...\nしかも この時計は一回しか使えない.")
    coroutine.yield()
    message.ShowMessage("勇者「僕が このチョコを食べれる世界はこないってことか...")
    coroutine.yield()
    message.ShowMessage("勇者「くやしいなぁ. XXちゃんの手作りチョコ. \n食べたかったなぁ...")
    coroutine.yield()
    message.ShowMessage("カッチ...カッチ...カッチ...")
    coroutine.yield()
    message.ShowMessage("勇者「まてよ...ここにあるじゃないか！")
    coroutine.yield()
    message.ShowMessage("カッチ...カッチ...カッチ...")
    coroutine.yield()
    message.ShowMessage("勇者「時間がない...\nどうしよう食べちゃおうか...")
    coroutine.yield()
    player.MoveTo("left",1)
    coroutine.yield()
    player.MoveTo("right",1)
    coroutine.yield()
    player.MoveTo("left",1)
    coroutine.yield()
    player.MoveTo("right",1)
    coroutine.yield()
    message.ShowMessage("過去勇者「あー今日もスライム討伐がんばったぞー！！")
    coroutine.yield()
    message.ShowMessage("勇者「(やべ！僕が帰ってくる.隠れないと.)")
    coroutine.yield()
    player.MoveTo("right", 2)
    coroutine.yield()
    player.MoveTo("up", 2)
    coroutine.yield()
    player.MoveTo("right", 4)
    coroutine.yield()
    player.MoveTo("up", 3)
    coroutine.yield()
    camera.JumpTo("up", 10)
    coroutine.yield()
    player.MoveTo("up", 4)
    coroutine.yield()
    player.MoveTo("left", 10)
    coroutine.yield()
    message.ShowMessage("過去勇者「うぎゃーー！！！")
    coroutine.yield()
    message.ShowMessage("カチ...")
    coroutine.yield()
    message.ShowMessage("勇者「もう時間がない...\nこうなったら食べちゃえ！！！")
    coroutine.yield()
    message.ShowMessage("勇者「(パクッ!)おいしぃ...おいしぃよ...")
    coroutine.yield()
    message.ShowMessage("勇者「(パクッ!)これが手作りチョコの味かぁ")
    coroutine.yield()
    message.ShowMessage("カチ...カチ...カチ...\nカチ!カチ!カチ!カチ!")
    coroutine.yield()
    message.ShowMessage("勇者「うわぁーーー！\nうわーー！！うわーー！！")
    coroutine.yield()
    fadePanel.PlayFadeOut()
    coroutine.yield()
    message.Wait(2)
    message.ClearMessage()
    fadePanel.PlayFadeIn()
    coroutine.yield()
    message.Wait(2)
    coroutine.yield()
    npcBoy.NormalSpeedPoint()
    coroutine.yield()
    message.ShowMessage("勇者「...は！戻ってきたのか！？")
    coroutine.yield()
    message.ShowMessage("勇者「ふぅ...危なかった \nもう少しでチョコが食べれないとこだった")
    coroutine.yield()
    message.ShowMessage("勇者「でも...\n犯人はいなかったわけだし")
    coroutine.yield()
    message.ShowMessage("勇者「いったいだれが \nあのチョコを食べたんたんだろう...")
    coroutine.yield()
    fadePanel.PlayFadeOut()
    coroutine.yield()
    message.Wait(2)
    coroutine.yield()
    message.ShowMessage("おしまい")
    coroutine.yield()
end