  function main()

    event.ShowMessage("みなさんこんにちは！")
    player.MoveTo("right", 4)
    coroutine.yield()
    event.ShowMessage("スタジオしまづの嶋津です")
    coroutine.yield()
    event.ShowMessage("Luaというものでゲームイベントの制御をしてみました。")
    coroutine.yield()
    event.ShowMessage("右に2つ進みます！")
    coroutine.yield()
    player.MoveTo("right", 2)
    coroutine.yield()
    event.ShowMessage("下に３つ下がります！")
    coroutine.yield()
    player.MoveTo("down", 3)
    coroutine.yield()
    event.ShowMessage("RPGのオープニングなどで使いやすいかな？")
    coroutine.yield()
  end